[package]

name = "tonico"

version = "0.1.0"

edition = "2024"

[dependencies]

tonic = { version = "^0.11.0" , features = ["tls"] }

prost = "^0.12.4"

[build-dependencies]

tonic-build = "^0.11.0"
